### ISSUE TITLE
Cookie 经常过期

### ISSUE THREAD

**Issue by Downstars** [sy-records/v-checkin#3]
浏览器能保存登陆状态很久，但是用脚本估计几个小时cookie就过期了，不知道作者有碰到这种情况吗？

**Comment by sy-records** [comment]
姿势有问题，我不改密码的话cookie一直有效，已经跑了好久了。
![image](https://user-images.githubusercontent.com/33931153/81489985-b6610d80-92ae-11ea-9821-659bed20dd26.png)
