### ISSUE TITLE
链接1成功，链接2未成功

### ISSUE THREAD

**Issue by mfgcs** [sy-records/v-checkin#4]
![image](https://user-images.githubusercontent.com/62247746/84112102-b6456080-aa5a-11ea-8536-369289933dab.png)
链接2显示成功，但是没有增加V力值。

**Comment by sy-records** [comment]
https://v.qq.com/x/bu/mobile_checkin 把这个链接在腾讯视频app里面打开下 下次就会自动了 7天打开一次。

**Comment by mfgcs** [comment]
> https://v.qq.com/x/bu/mobile_checkin 把这个链接在腾讯视频app里面打开下 下次就会自动了 7天打开一次。

ios系统，如何打开这个链接呢？

**Comment by sy-records** [comment]
关注一个好友，发私信给他就行
