### ISSUE TITLE
cookie过期速度太快

### ISSUE THREAD

**Issue by mfgcs** [sy-records/v-checkin#5]
cookie过期速度太快！如何解决？

**Comment by sy-records** [comment]
你配置写的有问题

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/84249143-f8df6980-ab3c-11ea-82e6-dccd57e1481a.png)
主要是这里，把粘贴上一步的cookie中的vqq_vusseion删掉，后面会补vqq_vusseion
