### ISSUE TITLE
手机版失效了吗

### ISSUE THREAD

**Issue by ghost** [sy-records/v-checkin#9]
双签那个手机签到是失效了吗，ck怎么弄都显示失效。

**Comment by sy-records** [comment]
没问题，应该是你配置的不对

**Comment by ghost** [comment]
我问了好几个人，他们都说不行了，说是手机版ck有效期一天

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/103718824-a0a11500-5002-11eb-8315-a5bd6289f39e.png)

我这里是ok的，只不过需要每7天自己点一次。

**Comment by ghost** [comment]
我就是按照你的教程，电脑版正常，就是手机那个链接，我进app点一次签到，第二天还是失效，哪里操作不对吗

**Comment by ghost** [comment]
sign_headers里的ck只留这个vqq_vusession=' + cookie['vqq_vusession'] + ';',原本的带值的vqq_vusession要整个删除吗？

**Comment by sy-records** [comment]
要

**Comment by ghost** [comment]
好的，我再试一下
